### PR TITLE
Fix README typo for site command

### PR DESCRIPTION
**Pull request by manico**
Fix `netlifyctl sites` to `netlifyctl site`.

### CODE REVIEW

**Comment by calavera** [comment]
Thanks for opening this 🙌 

`sites` is actually an alias, and it should work too:

https://github.com/netlify/netlifyctl/blob/master/commands/sites/sites.go#L17

It would be interesting to add the list of aliases to the readme to be more clear, if you want to do that.

**Comment by manico** [comment]
It does not work for me. :(
I'm on MacBook Pro High Siera.

**Comment by calavera** [comment]
You're probably using an older version:

```
➜  ~ netlifyctl version                             
64badcbad373780a6dae8607c3d0c676507884d4
➜  ~ netlifyctl sites                               
Site                                   Url
happy-borg-f26e76                      http://happy-borg-f26e76.netlify.com
preacher-perkin-51214                  http://preacher-perkin-51214.netlify.com
designer-manners-68256                 http://designer-manners-68256.netlify.com
advisor-offices-70685                  http://advisor-offices-70685.netlify.com
writer-runoff-67217                    http://writer-runoff-67217.netlify.com
```

You should be able to update with homebrew. The most recent version is 0.2.2.

**Comment by manico** [comment]
Yup, an older version.

**Pull request closed without merging**
